[package]
name = "kaitai"
version = "0.2.0"
authors = ["Bradlee Speice <bradlee@speice.io>", "Aon"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
encoding-next = "0.3"
cp437 = "*"
unicode-segmentation = "1.9.0"
flate2 = "1.0"
once_cell = "1.15.0"
bytes = "1.3.0"

[dev-dependencies]
tempfile = "3.4.0"